// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAplcaqyJgip7hgVrHFJ489BYCR7DppraU',
    appId: '1:1055928331681:web:b1485354c5275b460eafe0',
    messagingSenderId: '1055928331681',
    projectId: 'ecommerceapp-23071',
    authDomain: 'ecommerceapp-23071.firebaseapp.com',
    storageBucket: 'ecommerceapp-23071.firebasestorage.app',
    measurementId: 'G-78Q9EH08S6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUEmsLDnLznhVC8Vp3xqZLrxXjurEWc6Y',
    appId: '1:1055928331681:android:c12efa1eb3f68ecc0eafe0',
    messagingSenderId: '1055928331681',
    projectId: 'ecommerceapp-23071',
    storageBucket: 'ecommerceapp-23071.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAplcaqyJgip7hgVrHFJ489BYCR7DppraU',
    appId: '1:1055928331681:web:f4b99663305de2eb0eafe0',
    messagingSenderId: '1055928331681',
    projectId: 'ecommerceapp-23071',
    authDomain: 'ecommerceapp-23071.firebaseapp.com',
    storageBucket: 'ecommerceapp-23071.firebasestorage.app',
    measurementId: 'G-TFH8JFNH8H',
  );
}
