// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtW4PhSvu99xbYhdzQTtCr-Kb1gwWODF4',
    appId: '1:368516372145:web:671d4a8281252ffe4fb490',
    messagingSenderId: '368516372145',
    projectId: 'ecommerceapp-ab0bc',
    authDomain: 'ecommerceapp-ab0bc.firebaseapp.com',
    storageBucket: 'ecommerceapp-ab0bc.firebasestorage.app',
    measurementId: 'G-SJ22YEMZ67',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOwWYutfCLn_q6vMzQkdVjyMpvNNlMOwY',
    appId: '1:368516372145:android:fdb2bde13b2710694fb490',
    messagingSenderId: '368516372145',
    projectId: 'ecommerceapp-ab0bc',
    storageBucket: 'ecommerceapp-ab0bc.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtW4PhSvu99xbYhdzQTtCr-Kb1gwWODF4',
    appId: '1:368516372145:web:0e7f95eba2e8cfe54fb490',
    messagingSenderId: '368516372145',
    projectId: 'ecommerceapp-ab0bc',
    authDomain: 'ecommerceapp-ab0bc.firebaseapp.com',
    storageBucket: 'ecommerceapp-ab0bc.firebasestorage.app',
    measurementId: 'G-KB89DTKH1D',
  );

}